### ISSUE TITLE
partition issues? (partition ID)

### ISSUE THREAD

**Issue by eiiiiix** [CelesteBlue-dev/PSVita-StorageMgr#13]
according to the wiki these are the partitions
some are different than here
i dont know if they cause any problems so ill just point this out

sd0 0x1?
os0 0x3
vs0 0x4
vd0 0x5
tm0 0x6
ur0 0x7
ux0 0x8
gro0 0x9
grw0 0xA
ud0 0xB
sa0 0xC
pd0 0xE

**Comment by CelesteBlue-dev** [comment]
@eiiiiix and what is the diffence with StorageMgr mount IDs ?

**Comment by CelesteBlue-dev** [comment]
no issue really
