### ISSUE TITLE
Missing Apps

### ISSUE THREAD

**Issue by Rikimaruaxu** [CelesteBlue-dev/PSVita-StorageMgr#14]
I got an sd card after buying a sd2vita, and after getting this set up and working things worked. Then I rebooted after a live refresh. And now all my games and dlc are gone. As if they didn't exist. The space is still used on the sd card but the folders are just empty. Loaded up on pc on 3 different micro sd readers and all have the files just gone
Any idea or help would be great.
Also. Got an error 80070570 File or directory is corrupt
Err. just in case its needed. Phat vita with 3.65 enso. 64gb microsdcard

**Comment by Rikimaruaxu** [comment]
As a follow up. My sd2vita corrupts every time i go into sleep mode =/ I dont know what to do.

**Comment by Rikimaruaxu** [comment]
Nvm Got it working. I think. had to set allocation size to 32kb since both 64kb and default just flat out corrupted app and addcont on sleep and reboot. actually still afraid to reboot the vita now since it might corrupt for a 7th time. (tested sd card for fakeness, and the sd2vita is a brand new v5 so hopefully thats not the main issue) But yea this can be closed. Unless you can offer some tips.

**Comment by CelesteBlue-dev** [comment]
Not a StorageMgr issue.
