### ISSUE TITLE
PSVSD issues with h-encore

### ISSUE THREAD

**Issue by 9BitStrider** [CelesteBlue-dev/PSVita-StorageMgr#17]
After installing StorageMgr onto my 1101 Vita (3.68 + h-encore) using the PSVSD adaptor (SphereSolid version), h-encore seemed to crash during exit without actually turning the system off. I then received a message stating "Device is not supported" and neither my SD card (128GB) or my memory card (64 GB) were recognized by the Vita. This also gave every app installed a "File Corrupt" error when attempting to load them. (h-encore and VitaShell included). Reinstalling taiHen's config from h-encore solves the problem. [Log](https://pastebin.com/EhiuPcgD)

**Comment by SilentNightx** [comment]
Same issue here. usbmc doesn't work either. Memory card formatted correctly. Can be manually mounted in VitaShell

**Comment by CelesteBlue-dev** [comment]
Fixed by https://github.com/CelesteBlue-dev/PSVita-StorageMgr/commit/e1892a3842256fabafaa948168fdd3599b9f0505

**Comment by 9BitStrider** [comment]
Does this mean it's been compiled into the skprx? Or do we compile ourselves?

**Comment by CelesteBlue-dev** [comment]
@9BitStrider I just compiled v2.0, available in Release.
