### ISSUE TITLE
[h-encore 3.68] Mounting SD2VITA at uma0 does not remount on removal or sleep

### ISSUE THREAD

**Issue by Linkandzelda** [CelesteBlue-dev/PSVita-StorageMgr#18]
As the title says, mounting to uma0 and putting to sleep or removing the card will not remount the card. I'm using a 2000 on 3.68 and SD2VITA.

For what its worth, mounting to imc0 works fine, but for whatever reason this method does not work for Adrenaline.

**Comment by CelesteBlue-dev** [comment]
Duplicate as #16.
