### ISSUE TITLE
[3.68 MCD=uma0] disappears after suspend

### ISSUE THREAD

**Issue by 9BitStrider** [CelesteBlue-dev/PSVita-StorageMgr#24]
Mostly happens when the system is in sleep mode. When waking the system, uma0 will simply be gone. Also, how do I get rid of the system check for the SIM card board?

Firmware: 3.68
Ux0: 128 GB micro SD w/ SpheresSolid PSVSD adaptor
Uma0: Standard Vita memory card (64GB)

**Comment by CelesteBlue-dev** [comment]
Do you use StorageMgr v2.0 ?
Please send ur0:tai/storagemgr_log.txt when this uma0 issue happens.

**Comment by 9BitStrider** [comment]
Yes, and I will upload once it happens again.

**Comment by 9BitStrider** [comment]
Alright. I've encountered the error a few times while I was out and about and I'm almost sure it's caused by the following message when coming out of sleep mode:

"A problem occurred with a mobile network feature. Contact technical support for assistance. (C4-3575-0)"

Once this occurs, uma0: completely disappears from VitaShell and cannot be read by Adrenaline either (it acts as if a memory card is not inserted). Rebooting and reapplying h-encore fixes this... Until yo go into sleep mode fr a few minutes.

[Log](https://pastebin.com/Sk0BLJww)

**Comment by 9BitStrider** [comment]
One last bit of info. I found out how to disable the 3G error message using registry editor. However, uma0 still disappears on occassion with use_debug_options enabled.

**Comment by CelesteBlue-dev** [comment]
Please test : https://github.com/CelesteBlue-dev/PSVita-StorageMgr/releases/tag/v2.1b1

**Comment by 9BitStrider** [comment]
Seems to be working. I haven't encountered the issue since installing the plugin.
