### ISSUE TITLE
[GCD=ux0] Vita shuts down from sleep

### ISSUE THREAD

**Issue by mcmpresto** [CelesteBlue-dev/PSVita-StorageMgr#27]
my psvita slim running with sd2vita is shutting down from sleep whenever i enable storagemgr plugin, issue doesnt occur when storagemgr is disabled. 
my plugins
nonpdrm
taihen
henkaku

**Comment by CelesteBlue-dev** [comment]
Please show config.txt and storage-config.txt

**Comment by cvskid** [comment]
Thought i was the only one having this problem with the vita shutting down from being in sleep mode. I hope it's ok to post here so the same issue won't show up twice in 2 separate issue threads.

[config.txt](https://github.com/CelesteBlue-dev/PSVita-StorageMgr/files/2172952/config.txt)
[storage_config.txt](https://github.com/CelesteBlue-dev/PSVita-StorageMgr/files/2172953/storage_config.txt)

**Comment by mcmpresto** [comment]
@CelesteBlue-dev cvskid and i have the same config except that i dont have download enabler

**Comment by breakingspell** [comment]
Same here, on 3.65 Enso using both a v2 and v5 SD2Vita. Not sure of the interval when it shuts off from sleep, are there any other logs we could collect?

[config.txt](https://github.com/CelesteBlue-dev/PSVita-StorageMgr/files/2172972/config.txt)
[storage_config.txt](https://github.com/CelesteBlue-dev/PSVita-StorageMgr/files/2172973/storage_config.txt)

**Comment by jerrytom88888** [comment]
same here. this problem only with h-encore. works well with 3.65 enso which not hack with h-encore.

**Comment by CelesteBlue-dev** [comment]
Please send ur0:tai/ storagemgr_logs.txt

**Comment by XVaserteXXV** [comment]
I also have the same problem.
[config.txt](https://github.com/CelesteBlue-dev/PSVita-StorageMgr/files/2173827/config.txt)
[storage_config.txt](https://github.com/CelesteBlue-dev/PSVita-StorageMgr/files/2173828/storage_config.txt)
[storagemgr_log.txt](https://github.com/CelesteBlue-dev/PSVita-StorageMgr/files/2173829/storagemgr_log.txt)

**Comment by breakingspell** [comment]
[storagemgr_log.txt](https://github.com/CelesteBlue-dev/PSVita-StorageMgr/files/2173859/storagemgr_log.txt)

Only using an SD2Vita in a slim, no Sony memcard.

**Comment by cvskid** [comment]
[storagemgr_log.txt](https://github.com/CelesteBlue-dev/PSVita-StorageMgr/files/2173981/storagemgr_log.txt)

**Comment by stuermera** [comment]
Same here. Slim with 3.68 and H-Encore.

**Comment by CelesteBlue-dev** [comment]
Please test : https://github.com/CelesteBlue-dev/PSVita-StorageMgr/releases/tag/v2.1b1

**Comment by XVaserteXXV** [comment]
I tried the v2.1b1 and now I cannot use the touchscreen anymore

**Comment by CelesteBlue-dev** [comment]
Please test : https://github.com/CelesteBlue-dev/PSVita-StorageMgr/releases/tag/v2.1

**Comment by XVaserteXXV** [comment]
It now works thanks

**Comment by YuriSizuku** [comment]
Yes, when using  V2.1, this problem has been fixed. My vita won't shut down while sleeping.

**Comment by mcmpresto** [comment]
thanks its working now!
