### ISSUE TITLE
[GCD=ux0] C1-2569-2 errors on any app after suspend

### ISSUE THREAD

**Issue by Batyan45** [CelesteBlue-dev/PSVita-StorageMgr#29]
Randomly after leaving PS Vita Slim on sleep mode then I have C1-2569-2 errors on any app, also on Settings.
PS VIta Slim 3.68
Everything was ok on StorageMgr 1.2

**Comment by dmaskell92** [comment]
Also have the same problem

**Comment by CelesteBlue-dev** [comment]
Please send ur0:storagemgr_logs.txt and ur0:tai/storage_config.txt

**Comment by Batyan45** [comment]
[storage_config.txt](https://github.com/CelesteBlue-dev/PSVita-StorageMgr/files/2173780/storage_config.txt)
[storagemgr_log.txt](https://github.com/CelesteBlue-dev/PSVita-StorageMgr/files/2173781/storagemgr_log.txt)

**Comment by CelesteBlue-dev** [comment]
Please test : https://github.com/CelesteBlue-dev/PSVita-StorageMgr/releases/tag/v2.1b1

**Comment by dmaskell92** [comment]
It's been fixed with the latest version, cheers.
