### ISSUE TITLE
PSTV issues with sd2vita adapter

### ISSUE THREAD

**Issue by ccfman2004** [CelesteBlue-dev/PSVita-StorageMgr#33]
I have an sd2vita adapter that works perfectly fine with StorageMgr on my Vita-1000 but with the same setup I can't get it to work at all on my PSTV.  On the TV I have it setup where the internal memory card should mount as uma0 and the sd2vita should mount as ux0 but if the sd2vita adapter is inserted, the TV see no memory cards at all.

The sd card is setup properly as I can use it with my Vita-1000.

**Comment by CelesteBlue-dev** [comment]
please send ur0:tai/storagemgr_log.txt

**Comment by ccfman2004** [comment]
It started working for no apparent reason.  Not sure what I did.

**Comment by ccfman2004** [comment]
Still having issues.  How do I disable all plugins on the PSTV?  I tried holding L1 on the PS3 controller but it doesn't seem to do the trick.

**Comment by CelesteBlue-dev** [comment]
power off by maintaining POWER button. then reboot into Recovery Mode by maintaining POWER button.
Select Rebuild database.
It will reboot without loading plugins.

**Comment by ccfman2004** [comment]
Thanks, that did the trick.  I had an error in the config.txt file.  Whoops.
