### ISSUE TITLE
uma0 still fails to remount after Vita goes into sleep mode

### ISSUE THREAD

**Issue by itsminht** [CelesteBlue-dev/PSVita-StorageMgr#35]
I'm currently using:

- Vita 2000 model
- 32GB Sandisk Ultra microsd card
- 64GB Sony memory card
- storagemgr v2.1 

This seems to happen randomly whenever I leave my vita on sleep after a while. The only soft fix for this is to restart the Vita.  Also I like to add that the issue where the vita would randomly wake up to the lockscreen during its sleep is still present as of storagemgr version 2.1

@CelesteBlue-dev , It also seems like you've been asking this on other issues but yes I do have a Sony memory card inserted as I use it with my sd2vita as well. 

Storagemgr is configured as:

MCD = ux0
INT = imc0
GCD = uma0
(no UMA line as I do not use it)

Here is the log file:
[storagemgr_log.txt](https://github.com/CelesteBlue-dev/PSVita-StorageMgr/files/2194651/storagemgr_log.txt)

**Comment by Grazgamer** [comment]
I have the same config as above, tried 2 and 2.1. Constantly losing uma0. Was better before these versions.

**Comment by CelesteBlue-dev** [comment]
please try 1.2 and tell me

**Comment by Grazgamer** [comment]
I have been using 1.2 until yesterday and it was fine.

**Comment by BeemerDream** [comment]
Can 1.2 be used with 3.68 h-encore?

**Comment by Grazgamer** [comment]
It always seems to happen in Adrenaline. If I exit Adrenaline it seems to stay mounted. If it sleeps in Adrenaline, that’s when it disconnects.

**Comment by BeemerDream** [comment]
Thanks, i'll give it a try.

**Comment by trophywhale** [comment]
@CelesteBlue-dev version 1.2 has seem to fix the unmounting issue, haven't experienced it yet but I will update you later on if it happens again.

**Comment by SilentNightx** [comment]
Same but I'm using PSVSD.

**Comment by rsn8887** [comment]
I have a similar (same?) issue, using SD2Vita mounted as uma0: on 3.68, and storagemgr v2.1.

Everytime when my Vita is brought back from sleep, uma0: shows up as empty in Vitashell, no files or folders are listed. When this happens, apps fail to load any files from uma0:, and only a reboot fixes it. I tried re-running H-encore without reboot, but it doesn't fix it. Note uma0: is still showing up as a volume everywhere, and even the available free space is still shown correctly in Vitashell. But no files are shown.

**Comment by Javigracia** [comment]
Which release is 1.2? i don´t find it.

**Comment by BOBdotEXE** [comment]
here's 1.2:
https://github.com/CelesteBlue-dev/PSVita-StorageMgr/releases/tag/v1.2

**Comment by Grazgamer** [comment]
Tested again with 1.2 and 2.1. With 1.2 I lose the memory card every time it sleeps. With 2.1 I lose it every time it sleeps for a second time. After the first sleep the card is still available. I can repeatedly reproduce this.

**Comment by Grazgamer** [comment]
I have done some further testing and can confirm the following.

1.2

On first sleep and awaken, hma0 is no longer available.

2.0

Have tested 10 times with sleep and awaken. hma0 is always available.

2.1

On first sleep and awaken, hma0 is available.

On second sleep and awaken, hma0 is no longer available.

I have repeatedly tested this and can replicate each example multiple times.

Conclusion, 2.0 seems to be the better option.

**Comment by Avrution** [comment]
Same issues on 2.1 - Vita wakes up on its own from sleep and uma0 is "empty" - still shows the correct usage/free space in Vitashell.  Can unmount, but trying to remount says to insert usb.

Basically the same setup as the OP on 3.65 Enso.

**Comment by CelesteBlue-dev** [comment]
@itsminht @Grazgamer @BeemerDream @SilentNightx @rsn8887 please test v3.0.

**Comment by Avrution** [comment]
Will be trying it.  Thanks.

**Comment by Javigracia** [comment]
The first tests seem to work all right. My vita is in 3.60, sd2vita v3 microsd 128gb and storagemgr 3.0. No remount problems, no magic wakeups. All works

**Comment by Grazgamer** [comment]
@CelesteBlue-dev Based on my previous tests, looks great. Have awakened from sleep 10 times and it is still mounted. Thank you so much for this, it’s a great plugin.

**Comment by itsminht** [comment]
Haven't ran into any issues so far, will update you later if any issues pop up. Thank you for working on this!

**Comment by CelesteBlue-dev** [comment]
thanks
