### ISSUE TITLE
Use with no memory card?

### ISSUE THREAD

**Issue by lunalik2** [CelesteBlue-dev/PSVita-StorageMgr#37]
I'm going to guess this is a yes, but I can use everything normally without a vita memory card (only the sd2vita) once installing this, correct?

**Comment by lunalik2** [comment]
As in, if I were to set up adrenaline, it would set up on the memory card?

**Comment by CelesteBlue-dev** [comment]
in ur0:tai/storage_config.txt, you must have this line : 
GCD=ux0
It mounts your SD2VITA as ux0:.
Then you can install any app and it will be installed on the SD2VITA.

**Comment by lunalik2** [comment]
Yep, I figured it out later that day. Thanks anyways!
