### ISSUE TITLE
PS TV H-Encore 3.65 Enso. All actions with INT will cause ignoring of the UMA by the device.

### ISSUE THREAD

**Issue by fewrules** [CelesteBlue-dev/PSVita-StorageMgr#38]
Config lokking like:
MCD=uma0
INT=imc0
UMA=ux0
will cause my PS TV to ignore USB stick and load MCD as ux0. Trying to mount uma0 in VitaShell causing error 0x80010078. 
Deleting INT from config will turn everything to normal with UMA=ux0 and MCD=uma0. In that case VitaShell willl mount INT as imc0 without problems.

**Comment by CelesteBlue-dev** [comment]
please test v3.0

**Comment by fewrules** [comment]
Yeah, fixed now. Thanks.

**Comment by CelesteBlue-dev** [comment]
thanks
