### ISSUE TITLE
Not working on 3.65 ?

### ISSUE THREAD

**Issue by erfg12** [CelesteBlue-dev/PSVita-StorageMgr#4]
Just updated to 3.65 Henkaku.

I deleted the ux0:tai/config.txt file, edit the ur0:tai/config.txt added below Kernel to use ur0:tai/storagemgr.skprx restarted device and my PSVSD is not recognized. I'm using the default storage_config.txt

    # For users plugins, you must refresh taiHEN from HENkaku Settings for
    # changes to take place.
    # For kernel plugins, you must reboot for changes to take place.
    *KERNEL
    ur0:tai/storagemgr.skprx
    # henkaku.skprx is hard-coded to load and is not listed here
    *main
    # main is a special titleid for SceShell

**Comment by halferuga** [comment]
I'm basically in the same situation. Wanted to try this out after running gamesd; and thought it would be the perfect time to update after I finish the 3.65 process.

I'm using a phat Vita with SD2Vita; my config.txt is identical; my storage_config.txt looks like this

`MCD=uma0
INT=imc0
UMA=grw0
GCD=ux0`

**Comment by GunshipMarkII** [comment]
I might be wrong about this, but I think 3.65 version wasn't built&uploaded yet, hence why it isn't working ( for me too )

**Comment by erfg12** [comment]
@GunshipMarkII you might be right. Looks like just his initial release is there, not the 3.65 one.

**Comment by halferuga** [comment]
Oh, well that's embarassing

**Comment by eiiiiix** [comment]
i would be careful with this on 3.65
im still on 3.60 but when i misstype something on accident it will fail to boot and make it look like a softbirck
if you mess up with it boot with L held so you can change it to work again

**Comment by AyanamiRei1** [comment]
So anyone going to compile this?

**Comment by erfg12** [comment]
Just compiled it, still didn't work. 

https://drive.google.com/open?id=13BxOd4MWzUGAz2Mmto9S9If-9hTd945T

**Comment by andoryuu3** [comment]
**To everyone above:** make sure your Storagemgr config file is named "storage_config.txt" and not "storagemgr_config.txt". CelesteBlue had mistakenly called it "storagemgr_config.txt" in the readme and has since corrected it. However until the next release, the readme on release v1.0 still has the mistake. 

**To erfg12:** thanks for compiling and testing it! Out of curiosity, what does the Storagemgr log file say? If I remember correctly, it should just be a text file in ur0:tai/

**Comment by erfg12** [comment]
@andoryuu3 No logs at all. That's why I posted to TheFlow0 (which we all know doesn't answer tweets often) as I was concerned skpx files weren't being executed at all.

**Comment by andoryuu3** [comment]
Strange, but that certainly is an indicator that it's not running. 

On my 3.60 PSTV it generated the log file before I corrected "storagemgr_config.txt" to "storage_config.txt" (which is how I realized my config file wasn't being read: there was a note saying no config file found)

**Comment by ccfman2004** [comment]
The config.txt needs to be in ur:tai for the custom plugins to work.  The plugins do need to be in vs0:tai.  I used VitaRW to mount them as writable.  I still couldn't get the supposed 3.65 version of storagemgr to work but now nonpdrm does work with it installed to vs0:tai.

**Comment by ccfman2004** [comment]
You are correct that the plugins do indeed work from ur0:  Not sure why they didn't work before.  Right now there is no tai folder in ux0: which is what I want since I am waiting for my PSVSD to arrive.

**Comment by Dimensional** [comment]
Compiled the new version, still not working right.

**Comment by mart1n8891** [comment]
https://github.com/yifanlu/usbmc/releases TheOfficialFlow has updated usbmc to work with 3.65 and 3.67. It would be interesting to see whether this makes it easier for StorageMgr to work with 3.65.

**Comment by GabyPCgeeK** [comment]
Copied and Pasted a few lines of code from usbmc to make it work on 3.65.
Tested SD2Vita to imc0, psvsd to ux0, memory card to uma0.

[https://github.com/GabyPCgeeK/PSVita-StorageMgr/releases/latest](https://github.com/GabyPCgeeK/PSVita-StorageMgr/releases/latest)

**Comment by erfg12** [comment]
@GabyPCgeeK Tested with PSVSD and it works!

**Comment by CelesteBlue-dev** [comment]
@GabyPCgeeK please ask a pull request

**Comment by CelesteBlue-dev** [comment]
@GabyPCgeeK I've merged, please git clone, build it, test it and if working upload the skprx and send the link so I will add it to releases. Thank you very much.

**Comment by GabyPCgeeK** [comment]
Built it, tested it. Updated my release with the file.
[https://github.com/GabyPCgeeK/PSVita-StorageMgr/releases/tag/v1.0.mod](https://github.com/GabyPCgeeK/PSVita-StorageMgr/releases/tag/v1.0.mod)

**Comment by CelesteBlue-dev** [comment]
@erfg12 @halferuga @GunshipMarkII @eiiiiix @AyanamiRei1 @GabyPCgeeK 
Compiled skprx for 3.65 now available here:
https://github.com/CelesteBlue-dev/PSVita-StorageMgr/releases/tag/v1.1

**Comment by milkawax** [comment]
Thats Great stuff, now im only missing a Feature to switch config during boot to start an alternate config and all should be fine.... ;)

**Comment by IDBurner** [comment]
@milkawax Feature to swap config on boot has been added to my fork

https://github.com/IDBurner/PSVita-StorageMgr/releases/tag/v1.2

Hoping to pull request it with this one, but that is up to @CelesteBlue-dev

**Comment by CelesteBlue-dev** [comment]
I close this issue because 3.65 support was added.
