### ISSUE TITLE
VitaShell and Adrenaline give an error if you try to run them from the Sony memory card

### ISSUE THREAD

**Issue by Checcolino** [CelesteBlue-dev/PSVita-StorageMgr#41]
everything works ... only problem and when I choose to start vitashell or adrenaline that I own on the memory sony tells me damaged files ... how to correct the error? thank you so much

**Comment by itsminht** [comment]
What is your current storagemgr setup?

**Comment by CelesteBlue-dev** [comment]
I close this issue because it seams not caused by StorageMgr but by your setup. Reopen an issue if you need.
