### ISSUE TITLE
PS Vita automatically shut down 30s later after entering standby mode 

### ISSUE THREAD

**Issue by alex163aa** [CelesteBlue-dev/PSVita-StorageMgr#46]
PS Vita automatically shut down 30s later after entering standby mode 

It's PS Vita 1000, 3.65 system, henkaku. I am using sd2vita pro adapter

I tried 3.0 and 2.1. The same problem

**Comment by itsminht** [comment]
Please post storagemgr.log and storage_config.txt in ur0:tai folder OR ux0:tai depending where you put your plugins.


This is strange as everyone else including me no longer faces this problem; it should definitely be fixed as of v3.0.

**Comment by CelesteBlue-dev** [comment]
No answer, no issue anymore...
