### ISSUE TITLE
An error has occured in the following application. (C2-12828-1)

### ISSUE THREAD

**Issue by Mentlegenxd** [CelesteBlue-dev/PSVita-StorageMgr#48]
I get this when I start the app. It also says Saved Core File Succeded. ux0:data/psp2core-1535247659-0x00002728a9-eboot.bin.psp2dmp. Help please?

**Comment by Mentlegenxd** [comment]
SwitchSD2Vita.

**Comment by CelesteBlue-dev** [comment]
This is not related to StorageMgr I guess, but to SwitchSD2Vita. Report the issue there please: https://github.com/Applelo/SwitchSD2Vita/issues.
