### ISSUE TITLE
3.60 and 3.65: GCD as uma0 is not remounted after Suspend Mode

### ISSUE THREAD

**Issue by senkus** [CelesteBlue-dev/PSVita-StorageMgr#5]
Issue: sd2vita mounted as uma0 shows as empty in VitaShell after sleep.

Nothing actually gets deleted, but my Adrenaline games (memstick on uma0) failed to boot after sleep and crashed if they were already running. I am now on 3.65 (where it doesn't mount at all), but I did back up the logs and cfg. I was using both a V2 and V3 sd2vita adapter on a European PSV Slim.
[storage_config.txt](https://github.com/CelesteBlue-dev/PSVita-StorageMgr/files/1802424/storage_config.txt)
[storagemgr_log.txt](https://github.com/CelesteBlue-dev/PSVita-StorageMgr/files/1802425/storagemgr_log.txt)

**Comment by ccfman2004** [comment]
This plugin is currently not compatible with 3.65 yet.

**Comment by AyanamiRei1** [comment]
sd2vita has been updated by theflow https://github.com/TheOfficialFloW/gamecard-microsd

**Comment by ccfman2004** [comment]
That maybe so, but this is the plugin we want as we like to use both real memory card and the sd2vita or PSVSD.

**Comment by CelesteBlue-dev** [comment]
From you 3.60 log I can see : 
StorageMgrKernel finished with success.
suspend_workaround_callback.
Remounting uma0: 80010011.
suspend_workaround_callback.
Remounting uma0: 80010011.
I will check.

**Comment by IDBurner** [comment]
Do you mean empty? As in it shows uma0 in the list but nothing is in there. Or do you mean that after sleep that uma0 does not show in the list and needs to be remounted?

That is the behavior I am experiencing. I have been battling that on usbmc as well and have not yet found a solution to this bug. I swapped here in hopes that it was fixed in this build but alas.

**Comment by senkus** [comment]
Yes, I do mean empty. All it lists is ".." for Up. Now, on 3.65, I'm using a fork of gamesd that mounts sd2vita at uma0. Works fine. Should be in my starred repos if you need it.

**Comment by CelesteBlue-dev** [comment]
@senkus Please try latest storagemgr.skprx it should work on 3.65.

**Comment by senkus** [comment]
I tried it just now. Put the Vita to sleep for a few times, manually and via idle -- no more issues. Good job and many thanks!

**Comment by senkus** [comment]
Here's the log again. At first, I had incorrect settings, so disregard anything relating to UMA=uma0.
[storagemgr_log.txt](https://github.com/CelesteBlue-dev/PSVita-StorageMgr/files/1825744/storagemgr_log.txt)

**Comment by IDBurner** [comment]
When you goto VitaSHell and hit Triangle is there an option to remount UMA .. and if so does it mount properly?

**Comment by senkus** [comment]
@IDBurner There options I get are:

Mount uma0: (grey)
Mount imc0: (grey)

Mount USB ux0: (white)
Unmount USB ux0: (grey)

VitaShell 1.83 Unsafe Mode

**Comment by GrayJack** [comment]
I have not problems with my proprietary Sony card mounted as uma0, even after the device sleeps

**Comment by dmaskell92** [comment]
Well UMA0 is currently hidden for me as we speak. Not sure why, I can provide my .log if it would help anyone.

**Comment by IDBurner** [comment]
I have found UMA0 to be shotty to be honest. It requires a lot of poking to keep up.

Could people post which Vuta the have? Fat, 3G, slim, etc... It may help

**Comment by dmaskell92** [comment]
3G 1000

PSVSD - UX0 - 64GB
SD2VITA - GRW0 - 32GB
Sony - UMA0 - 32GB

**Comment by IDBurner** [comment]
I would be interested to see the model @GrayJack has as well.

**Comment by TheRadziu** [comment]
both mount points work for me with no issues, never get unmounted during suspend. 

SD2vita - UX0 - 64GB
Vita Mem - UMA0 - 32GB

Wifi Fatty vita

**Comment by GrayJack** [comment]
3G PCH-1101

PSVSD - UX0 - 128GB
Sony - UMA0 - 32GB

Using the latest release

**Comment by CelesteBlue-dev** [comment]
Fixed by #22.

**Comment by chashodges** [comment]
Currently having this same issue using newest most up to date version of Storage Manager. I have SD2vita set as Uma0 - works after reboot, if console sleeps for more than a few minutes console needs s restart to be rediscovered.
