### ISSUE TITLE
Battery drain

### ISSUE THREAD

**Issue by azumukupoe** [CelesteBlue-dev/PSVita-StorageMgr#52]
The plugin drains battery while vita is being left slept.
And https://github.com/Electry/VitaStorage/ is also available.

**Comment by Urbs97** [comment]
Does only StorageMgr drain power or did you already test the other plugins like "gamesd"?

**Comment by azumukupoe** [comment]
I'm using gamesd because it doesn't drain

**Comment by Urbs97** [comment]
The problem is the latest version of gamesd doesnt support mounting the mem card as uma0.

**Comment by SiTWulf** [comment]
I can confirm... complete drain my battery.
The only plugin can work without battery drain is [SwitchSD2Vita](https://github.com/Applelo/SwitchSD2Vita) 1.3

**Comment by TheRadziu** [comment]
SwitchSD2vita is not a plugin, it's an plugin installer (homebrew) which uses storagemgr 3.0 in latest version and probably forks of gamesd in mentioned 1.3v

To contribute to this thread/issue: I'm using StorageMgr v3.0 and I dont have any wakeups (just confirming the 3.0 fix) nor battery drain, in fact my vita has been left unused for 30 days on standby and when I came back to it, battery drain was close to zero.

**Comment by richard1222** [comment]
I use storagemgr v3 also and i can confrim to the battery does not drain fast at all. I also bought mine used off ebay  if that means anything

**Comment by SiTWulf** [comment]
Im using Storagemgr v3 for a few days and not get any battery drain...
Looks like the V3 not have these battery drain bug...

**Comment by CelesteBlue-dev** [comment]
This has no link with StorageMgr plugin.
