### ISSUE TITLE
Format Loop with physical cartridge

### ISSUE THREAD

**Issue by crescentm00n** [CelesteBlue-dev/PSVita-StorageMgr#60]
So when I insert a game cartridge hoping the mount point will be redirected to my MCD as uma0, it goes into a format loop unless I hit cancel in which will ask me to format again if I pop in the game later on the homescreen (I formatted regardless just to see results because I have my files backed up). Storage_config.txt and the skprx are in ur0:tai and skprx is under the kernel properly spelled along with the rest of my plugins in the config.txt via ur0:tai. In storage_config.txt, I left only MCD=uma0 and GCD=ux0 for my Vita 1000. I do not have gamecard2sd.skprx loaded. What else could be causing my conflict?

**Comment by CelesteBlue-dev** [comment]
Why are you mounting game cartridge as ux0 ? (GCD=ux0) This line is only for mointing SD2VITA as ux0.
