### ISSUE TITLE
My ps vita doesn't detect SD2VITA.

### ISSUE THREAD

**Issue by Aukiv** [CelesteBlue-dev/PSVita-StorageMgr#61]
My ps vita doesn't detect SD2VITA, I've tried everything but I've been able to do it, if they could help me.

> StorageMgrKernel v3.0 started.
> system_sw_version: 03600000
> Installing SceSblSsMgr hook...
> tm0 : tm0:
> exfattm0
> sdstor0:int-lp-ign-vtrm
> (null)
> 00000500
> 
> ur0 : ur0:
> exfatur0
> sdstor0:int-lp-ign-user
> (null)
> 00000600
> 
> ux0 : ux0:
> exfatux0
> sdstor0:xmc-lp-ign-userext
> (null)
> 00000800
> 
> gro0 : gro0:
> exfatgro0
> sdstor0:gcd-lp-ign-gamero
> (null)
> 00000900
> 
> grw0 : grw0:
> exfatgrw0
> sdstor0:gcd-lp-ign-gamerw
> (null)
> 00000A00
> 
> imc0 : imc0:
> exfatimc0
> sdstor0:int-lp-ign-userext
> (null)
> 00000D00
> 
> xmc0 : xmc0:
> exfatxmc0
> sdstor0:xmc-lp-ign-userext
> (null)
> 00000E00
> 
> uma0 : uma0:
> exfatuma0
> sdstor0:uma-pp-act-a
> sdstor0:uma-lp-act-entire
> 00000F00
> 
> mount point id : 0x0800
> Reading current device blkdev for mount point 0x800 :
> sdstor0:xmc-lp-ign-userext
> current blkdev : sdstor0:xmc-lp-ign-userext (null)
> Is ux0: redirected : 0
> ux0: current device : sdstor0:xmc-lp-ign-userext (null)
> Reading config...
> Checking if UMA is in config.
> Reading config...
> Reading config...
> Line of size 8 : MCD=uma0
> Reading config...
> Line of size 7 : GCD=ux0
> Checking if GCD is in config.
> Reading config...
> Reading config...
> Line of size 8 : MCD=uma0
> Reading config...
> Line of size 7 : GCD=ux0
> Checking if MCD is in config.
> Reading config...
> Reading config...
> Line of size 8 : MCD=uma0
> Checking if INT is in config.
> Reading config...
> Reading config...
> Line of size 8 : MCD=uma0
> Reading config...
> Line of size 7 : GCD=ux0
> No UMA config found.
> GCD config found at line 1.
> GC2SD detection...
> GC2SD not detected.
> Reading mount point for line 1...
> Reading config...
> Line of size 7 : GCD=ux0
> Line length : 7.
> Not read string length (device string) : 4.
> Current line mount point of string length 3 : ux0
> No INT config found.
> MCD config found at line 0.
> MCD detection...
> MCD detected.
> Reading mount point for line 0...
> Reading config...
> Line of size 8 : MCD=uma0
> Line length : 8.
> Not read string length (device string) : 4.
> Current line mount point of string length 4 : uma0
> mount is now : sdstor0:xmc-lp-ign-userext
> mount point id : 0x0800
> Reading current device blkdev for mount point 0x800 :
> sdstor0:xmc-lp-ign-userext
> current blkdev : sdstor0:xmc-lp-ign-userext (null)
> Is ux0: redirected : 0
> ux0: current device : sdstor0:xmc-lp-ign-userext (null)
> mount point id : 0x0A00
> Reading current device blkdev for mount point 0xA00 :
> sdstor0:gcd-lp-ign-gamerw
> current blkdev : sdstor0:gcd-lp-ign-gamerw (null)
> Is grw0: redirected : 0
> grw0: current device : sdstor0:gcd-lp-ign-gamerw (null)
> mount point id : 0x0F00
> Reading current device blkdev for mount point 0xF00 :
> sdstor0:xmc-lp-ign-userext
> current blkdev : sdstor0:xmc-lp-ign-userext (null)
> Is uma0: redirected : 1
> uma0: current device : sdstor0:xmc-lp-ign-userext (null)
> StorageMgrKernel finished starting with success.
>

**Comment by ap-401** [comment]
I faced the same problem and the same exact error in my log file: 

GC2SD detection...
GC2SD not detected.

The issue was with the formatting of my SD card. I formatted using the Disk Utility in Mac and it was leaving the default partition of the SD card. I was able to format it correctly in Terminal. Commands below:

diskutil list
diskutil unmount /dev/disk2s1
sudo newfs_exfat -R /dev/disk2

**Comment by craigerrington** [comment]
I just wanted to comment to say that the fix mentioned by @ap-401 was the same for me.

The new Disk Utility leaves a lot to be desired. Manually setting the card in the terminal seems like the most sure fire way to do this on a Mac.

**Comment by Aukiv** [comment]
I already solved it, it was my sd2vita that was defective, I had a 2.0 and now I bought a 3.0 works perfect.

**Comment by nezumisama** [comment]
I have the Chinese v5 (white with black text) SD2VITA adapter. I had the same problem, and it turned out to be a hardware problem. I removed the adapter, pressed the MicroSD card into it a bit, and poped it back, after lo and behold, after a reboot I had it mounted as ux0! I wish the error message was a little bit specific.

**Comment by QuantumMobileDevelopment** [comment]
I was also getting the same exact error in my log.
Thank you ap-401
diskutil list
diskutil unmount /dev/disk2s1
sudo newfs_exfat -R /dev/disk2
Fixed it.
