### ISSUE TITLE
3.70 support

### ISSUE THREAD

**Issue by nickxab** [CelesteBlue-dev/PSVita-StorageMgr#66]
Hello ! :)
Do you plan to update it for 3.70  cause it ain't working :(

**Comment by Duckbuster** [comment]
I recommend that you just downgrade to 3.60 or 3.65 and use Enso, and then this plugin.
Use modoru to downgrade:
https://github.com/TheOfficialFloW/modoru/blob/master/README.md

**Comment by nickxab** [comment]
yeah i was thinking the same cause none of the plugins works with 3.70 :/
Too bad it would be cool to have these things in 3.70 :P

**Comment by windsurfer1122** [comment]
+1 for 3.69/3.70 support
Just see release v1.5 of xyzz's [gamecard-microsd](https://github.com/xyzz/gamecard-microsd).

**Comment by CelesteBlue-dev** [comment]
Done in https://github.com/CelesteBlue-dev/PSVita-StorageMgr/commit/dce4000a7eb5c4d359ea4913a00fa7f8552cdd52.
