### ISSUE TITLE
how to fix Memory 256 ( use 50% ) but Read 210GB/ 233GB ?

### ISSUE THREAD

**Issue by NuKEInnerCorEarth** [CelesteBlue-dev/PSVita-StorageMgr#68]
Any solution ?
Is My StorageMgr Need to Replace ?

**Comment by CelesteBlue-dev** [comment]
Please explain better, post screenshots and logs found in ur0:tai/

**Comment by d-rez** [comment]
@ErickSavior make a backup of SD, reformat your SD card with exfat and make sure to select 64kB cluster size, then restore files onto the SD

**Comment by CelesteBlue-dev** [comment]
I approve @d-rez solution. If you still have this issue @NuKEInnerCorEarth, reopen an issue.
