### ISSUE TITLE
[GCD] PSVita wakeup issue

### ISSUE THREAD

**Issue by Javigracia** [CelesteBlue-dev/PSVita-StorageMgr#7]
Psvita continue waking up when I suspend it... I thought that it was fixed with storagemgr

**Comment by CelesteBlue-dev** [comment]
it's not fixed yet

**Comment by JuanD817** [comment]
It keeps happening after 2.1 update

**Comment by Cade-H** [comment]
Same here unfortunately, this is the only issue keeping StorageMgr from being perfect imo.

**Comment by CelesteBlue-dev** [comment]
Pleasr make a video.

**Comment by Javigracia** [comment]
ok, but the screen lights up in random time and the crash of games or apps after exiting suspension also. I'll try to record it and cut the video this afternoon.

**Comment by dmaskell92** [comment]
Not sure if this can be fixed, it's been a common issue since 3.60 and PSVSD/SD2VITA where first created.

**Comment by Javigracia** [comment]
I think it's an sd2vita bug that interferes with the storagemgr and is not just getting fixed at the root. But I don't know how all this works. It's just ideas.

**Comment by Javigracia** [comment]
Here the video link in my dropbox... This happen sometimes after suspend vita... Is like partition was unmounted I think. [Video showing start app error](https://www.dropbox.com/s/fynxxgjjacqp44w/20180709_193355_1.mp4?dl=0)

**Comment by CelesteBlue-dev** [comment]
please send ur0:tai/storagemgr_logs.txt

**Comment by Javigracia** [comment]
Here is the log
https://www.dropbox.com/s/inzit4ryn8e9jl5/storagemgr_log.txt?dl=0
Thanks

**Comment by CelesteBlue-dev** [comment]
do you have a memory card inserted ?

**Comment by JuanD817** [comment]
Just tested to see if the issue happens without my sd2vita inserted, it keeps happening, the blue led lights up and then the screen wakes up, at least i know that the adapter isn't the problem

**Comment by Javigracia** [comment]
Yes, i have Sony memory with 32gb space (but i don't use it with apps or emus, only for dump my own games in the past) and sd2vita with microsd 128gb in game catridge slot.

**Comment by stuermera** [comment]
I can confirm.
2.1 update installed, sd2vita 3.0 card with 128 GB Sandisk microSD.
Firmware 3.68 with H-encore.
I am using the standard config file for storagemgr.

**Comment by CelesteBlue-dev** [comment]
@JuanD817 @Javigracia @dmaskell92 @stuermera @GabyPCgeeK please test v3.0.

**Comment by Javigracia** [comment]
Ok, lets go. Tomorrow I'll try it and report you. Thanks

**Comment by JuanD817** [comment]
@CelesteBlue-dev just installed, ill report back in 2 hours

**Comment by Javigracia** [comment]
@CelesteBlue-dev The first tests seem to work all right. My vita is in 3.60, sd2vita v3 microsd 128gb and storagemgr 3.0. No remount problems, no magic wakeups. All works

**Comment by stuermera** [comment]
Working here on 3.68 and sd2vita.
Also it is much faster after waking up the device from standby.

**Comment by CelesteBlue-dev** [comment]
thanks
