### ISSUE TITLE
For 3.63 firmware

### ISSUE THREAD

**Issue by fekito** [CelesteBlue-dev/PSVita-StorageMgr#71]
I can't do it work on my Psvita 3.63 fat. I did all the steps. Is it not compatible?

**Comment by CelesteBlue-dev** [comment]
It is not. "Only" FWs 3.60, 3.65, 3.67, 3.68, 3.69, 3.70, 3.71, 3.72 and 3.73 are supported right now. Please update to 3.65 or downgrade to 3.60. And this way you would also benefit from enso (3.60 or 3.65).
