### ISSUE TITLE
README.MD says "storagemgr_config.txt" but release file is "storage_config.txt"

### ISSUE THREAD

**Issue by windsurfer1122** [CelesteBlue-dev/PSVita-StorageMgr#8]
What's the correct file name to use?

**Comment by CelesteBlue-dev** [comment]
fixed

**Comment by windsurfer1122** [comment]
Side note for README.md: it is "ex**a**mple" not "ex**e**mple"

**Comment by CelesteBlue-dev** [comment]
sorry in French it is "exemple" and in Spanish "ejemplo" so I though that in English it was a ''e too...
fixed

**Comment by windsurfer1122** [comment]
There are still some "Exemple" in the README.MD after Usage point 7 ;)

```
## Exemple:
![exemple_config](https://user-images.githubusercontent.com/20444249/37112629-46eb83dc-2243-11e8-8aae-c6ff36478c0a.jpg)
![exemple_vitashell](https://user-images.githubusercontent.com/20444249/37112630-4712d5f4-2243-11e8-9da9-29d1750d8767.png)

```

**Comment by CelesteBlue-dev** [comment]
@windsurfer1122 thanks 👍
https://github.com/CelesteBlue-dev/PSVita-StorageMgr/commit/99201fc0617c7ad8698f8b9e9736533634284050
