### ISSUE TITLE
someone can build a new version?

### ISSUE THREAD

**Issue by realcontra** [CelesteBlue-dev/PSVita-StorageMgr#9]
last few days the psvital 3.65 has supported . but release is seven days ago. someone can update it ？

**Comment by TheBooPanda** [comment]
Even the latest version doesn't work yet, people in issue #4 had this tested, also CelesteBlue posted some update on Twitter that states there's still work to be done to support 3.65.

So, be patient, eventually working version will be released.

**Comment by GabyPCgeeK** [comment]
Copied and Pasted a few lines of code from usbmc to make it work on 3.65.
Tested SD2Vita to imc0, psvsd to ux0, memory card to uma0.

[https://github.com/GabyPCgeeK/PSVita-StorageMgr/releases/latest](https://github.com/GabyPCgeeK/PSVita-StorageMgr/releases/latest)

**Comment by CelesteBlue-dev** [comment]
https://github.com/CelesteBlue-dev/PSVita-StorageMgr/releases/tag/v1.1
